Add postmark
pentacent/keila pull request #178
Opened 2023-01-11 09:25 UTC by aej

Resolves https://github.com/pentacent/keila/issues/176

2023-01-12 12:24 UTC, wmnnd requested changes
Looking good, except for one tiny typo in the Readme file!

2023-01-12 12:26 UTC, aej commented on README.md
> +For larger newsletter projects, AWS SES, Sendgrid, Mailgun and Postmark are supported in addition
```suggestion
For larger newsletter projects, AWS SES, Sendgrid, Mailgun, and Postmark are supported in addition
```

2023-01-12 12:27 UTC, aej commented on README.md
> +For larger newsletter projects, AWS SES, Sendgrid, Mailgun and Postmark are supported in addition
Done

2023-01-12 12:34 UTC, wmnnd commented
Thank you for contributing to Keila :partying_face:

2023-01-12 12:34 UTC, merged

2023-01-18 10:43 UTC, aej commented
I've just deployed my own instance of Keila and tried out the new Postmark integration end-to-end. I can confirm it all worked as expected 🎉

2023-01-18 11:54 UTC, wmnnd commented
Awesome, thanks for sharing! By the way, if you are serious about using Postmark, you might want to consider adding support for Postmark webhooks for bounces and spam complaints. You can see how I implemented this for SES here: https://github.com/pentacent/keila/blob/main/lib/keila_web/controllers/ses_webhook_controller.ex

2023-01-18 11:57 UTC, aej commented
> Awesome, thanks for sharing! By the way, if you are serious about using Postmark, you might want to consider adding support for Postmark webhooks for bounces and spam complaints. You can see how I implemented this for SES here: https://github.com/pentacent/keila/blob/main/lib/keila_web/controllers/ses_webhook_controller.ex

Ah yep - I built these out in my own app (which has its own separate Postmark integration) so I think I could add these pretty easily. Right now I dont have a need for webhook handling in Keila, but as soon as I do I'll add it in.