Feature/upsert on import
pentacent/keila pull request #94
Opened 2021-12-06 13:55 UTC by gbottari

Implements the import feature described at #87.

- now on `Keila.Contacts.import_csv` there's an extra parameter called `:on_conflict` that can either be `:replace` or `:ignore`
- if set to `:replace`, duplicated contacts (as detected by the e-mail) will be replaced with the latest ones found in the import file
- if set to `:ignore`, duplicated contacts found will always be skipped
- on the UI there's now a checkbox that controls this behavior and is set by default to replace

2021-12-06 15:59 UTC, wmnnd requested changes
Looking great! Thanks for this PR. :+1: 

I just added two small comments, please let me know if you can take care of them :slightly_smiling_face:

2021-12-06 15:59 UTC, wmnnd commented on lib/keila_web/live/contact_import_live.ex
> +    # IO.inspect(params)
Leftover `IO.inspect` :smile:

2021-12-06 15:59 UTC, wmnnd commented on lib/keila/contacts/import.ex
>    def import_csv(project_id, filename, opts) do
Could you document the options here?

2021-12-06 17:45 UTC, panoramix360 commented on lib/keila_web/live/contact_import_live.ex
> +    # IO.inspect(params)
Done!

2021-12-06 17:45 UTC, panoramix360 commented on lib/keila/contacts/import.ex
>    def import_csv(project_id, filename, opts) do
Done!

2021-12-06 18:01 UTC, panoramix360 commented
@wmnnd if you have another issue in mind for us (me and @gbottari) let us known.

In the meantime, we'll search for another one.

2021-12-08 20:21 UTC, wmnnd approved these changes

2021-12-08 20:22 UTC, merged

2021-12-08 20:23 UTC, wmnnd commented
Thank you for contributing to Keila, @gbottari and  @panoramix360! :pray: